/* eslint-disable no-console */
// One-time enrichment: pulls the top-billed cast for every catalog movie
// from OMDb (the same source the poster art came from) and writes
// src/data/cast.js. The app never calls OMDb at runtime.
//
// Usage (needs your OMDb API key — https://www.omdbapi.com/apikey.aspx):
//   OMDB_API_KEY=yourkey node scripts/fetch-cast.js
// PowerShell:
//   $env:OMDB_API_KEY="yourkey"; node scripts/fetch-cast.js
//
// Safe to re-run: it rewrites cast.js from scratch, keeping any entries
// OMDb couldn't find this time if a previous run had them.

const fs = require("fs");
const path = require("path");
const Module = require("module");
const babel = require("@babel/core");

const ROOT = path.join(__dirname, "..");
const MOVIES_FILE = path.join(ROOT, "src", "data", "movies.js");
const CAST_FILE = path.join(ROOT, "src", "data", "cast.js");
const CAST_PER_MOVIE = 4;
const DELAY_MS = 120;

const API_KEY = process.env.OMDB_API_KEY;
if (!API_KEY) {
  console.error("Set OMDB_API_KEY first (see the top of this file).");
  process.exit(1);
}

// movies.js is an ES module written for Metro — compile it to CommonJS to
// read the catalog from plain Node.
const loadModule = (file) => {
  const { code } = babel.transformFileSync(file, {
    presets: ["babel-preset-expo"],
    plugins: ["@babel/plugin-transform-modules-commonjs"],
    babelrc: false,
    configFile: false,
  });
  const mod = { exports: {} };
  const localRequire = Module.createRequire(file);
  const requireWithBabel = (request) => {
    if (request.startsWith(".")) {
      const resolved = localRequire.resolve(request);
      return loadModule(resolved);
    }
    return localRequire(request);
  };
  new Function("module", "exports", "require", code)(
    mod,
    mod.exports,
    requireWithBabel,
  );
  return mod.exports;
};

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// Titles OMDb can't match by title + year (it lists them a year off, or
// under a different title — "Seven", "WALL·E"), looked up by IMDb id.
const IMDB_IDS = {
  "The Deer Hunter|1978": "tt0077416",
  "Schindler's List|1993": "tt0108052",
  "Se7en|1995": "tt0114369",
  "Memento|2000": "tt0209144",
  "WALL-E|2008": "tt0910970",
};

const fetchCast = async (movie) => {
  const imdbId = IMDB_IDS[`${movie.title}|${movie.year}`];
  const query = new URLSearchParams(
    imdbId
      ? { apikey: API_KEY, i: imdbId }
      : { apikey: API_KEY, t: movie.title, y: String(movie.year), type: "movie" },
  );
  let response = await fetch(`https://www.omdbapi.com/?${query}`);
  let data = await response.json();
  // A few titles are listed a year off on OMDb — retry without the year.
  if (data.Response !== "True" && !imdbId) {
    query.delete("y");
    response = await fetch(`https://www.omdbapi.com/?${query}`);
    data = await response.json();
  }
  if (data.Response !== "True" || !data.Actors || data.Actors === "N/A") {
    return null;
  }
  return data.Actors.split(",")
    .map((name) => name.trim())
    .filter(Boolean)
    .slice(0, CAST_PER_MOVIE);
};

const main = async () => {
  const { MOVIES } = loadModule(MOVIES_FILE);
  let previous = {};
  if (fs.existsSync(CAST_FILE)) {
    try {
      previous = loadModule(CAST_FILE).CAST ?? {};
    } catch {
      previous = {};
    }
  }

  const cast = {};
  const missing = [];
  for (const movie of MOVIES) {
    try {
      const actors = await fetchCast(movie);
      if (actors) cast[movie.id] = actors;
      else if (previous[movie.id]) cast[movie.id] = previous[movie.id];
      else missing.push(`${movie.title} (${movie.year})`);
    } catch (error) {
      if (previous[movie.id]) cast[movie.id] = previous[movie.id];
      missing.push(`${movie.title} (${movie.year}) — ${error.message}`);
    }
    process.stdout.write(".");
    await sleep(DELAY_MS);
  }
  process.stdout.write("\n");

  const body = Object.entries(cast)
    .map(([id, actors]) => `  ${id}: ${JSON.stringify(actors)},`)
    .join("\n");
  fs.writeFileSync(
    CAST_FILE,
    `// Top-billed cast per catalog movie, from OMDb — generated by\n` +
      `// scripts/fetch-cast.js (a one-time enrichment, not a live API call).\n` +
      `// Re-run that script to refresh; don't edit by hand.\n` +
      `export const CAST = {\n${body}\n};\n\nexport default CAST;\n`,
  );

  console.log(`Wrote cast for ${Object.keys(cast).length}/${MOVIES.length} movies.`);
  if (missing.length > 0) {
    console.log(`No cast found for ${missing.length}:`);
    missing.forEach((line) => console.log(`  - ${line}`));
  }
};

main();
