/* eslint-disable no-console */
// One-time enrichment: pulls extra facts for every catalog movie from OMDb
// (critic scores, awards, age rating, language, country, writers, box
// office) and writes src/data/details.js. The app never calls OMDb at
// runtime — same approach as scripts/fetch-cast.js.
//
// Usage (needs an OMDb API key — https://www.omdbapi.com/apikey.aspx):
//   OMDB_API_KEY=yourkey node scripts/fetch-details.js
// PowerShell:
//   $env:OMDB_API_KEY="yourkey"; node scripts/fetch-details.js

const fs = require("fs");
const path = require("path");
const Module = require("module");
const babel = require("@babel/core");

const ROOT = path.join(__dirname, "..");
const MOVIES_FILE = path.join(ROOT, "src", "data", "movies.js");
const DETAILS_FILE = path.join(ROOT, "src", "data", "details.js");
const DELAY_MS = 120;

const API_KEY = process.env.OMDB_API_KEY;
if (!API_KEY) {
  console.error("Set OMDB_API_KEY first (see the top of this file).");
  process.exit(1);
}

// Titles OMDb can't match by title + year (listed a year off, or under a
// different title), looked up by IMDb id instead.
const IMDB_IDS = {
  "The Deer Hunter|1978": "tt0077416",
  "Schindler's List|1993": "tt0108052",
  "Se7en|1995": "tt0114369",
  "Memento|2000": "tt0209144",
  "WALL-E|2008": "tt0910970",
  "Amelie|2001": "tt0211915",
};

const loadModule = (file) => {
  const { code } = babel.transformFileSync(file, {
    presets: ["babel-preset-expo"],
    plugins: ["@babel/plugin-transform-modules-commonjs"],
    babelrc: false,
    configFile: false,
  });
  const mod = { exports: {} };
  const localRequire = Module.createRequire(file);
  const requireWithBabel = (request) =>
    request.startsWith(".")
      ? loadModule(localRequire.resolve(request))
      : localRequire(request);
  new Function("module", "exports", "require", code)(
    mod,
    mod.exports,
    requireWithBabel,
  );
  return mod.exports;
};

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const clean = (value) => (value && value !== "N/A" ? value.trim() : null);

const fetchOmdb = async (movie) => {
  const imdbId = IMDB_IDS[`${movie.title}|${movie.year}`];
  const query = new URLSearchParams(
    imdbId
      ? { apikey: API_KEY, i: imdbId }
      : { apikey: API_KEY, t: movie.title, y: String(movie.year), type: "movie" },
  );
  let data = await (await fetch(`https://www.omdbapi.com/?${query}`)).json();
  if (data.Response !== "True" && !imdbId) {
    query.delete("y");
    data = await (await fetch(`https://www.omdbapi.com/?${query}`)).json();
  }
  return data.Response === "True" ? data : null;
};

const toDetails = (data) => {
  const rating = (source) =>
    clean(data.Ratings?.find((entry) => entry.Source === source)?.Value);
  const rottenTomatoes = rating("Rotten Tomatoes");
  const metacritic = rating("Metacritic");
  return {
    imdbId: clean(data.imdbID),
    // The real IMDb score (the catalog's own rating was mock data).
    imdbRating: clean(data.imdbRating) ? parseFloat(data.imdbRating) : null,
    rated: clean(data.Rated),
    language: clean(data.Language),
    country: clean(data.Country),
    writers: clean(data.Writer),
    awards: clean(data.Awards),
    boxOffice: clean(data.BoxOffice),
    // "89%" → 89, "82/100" → 82
    rottenTomatoes: rottenTomatoes ? parseInt(rottenTomatoes, 10) : null,
    metacritic: metacritic ? parseInt(metacritic, 10) : null,
  };
};

const main = async () => {
  const { MOVIES } = loadModule(MOVIES_FILE);
  const details = {};
  const missing = [];
  for (const movie of MOVIES) {
    try {
      const data = await fetchOmdb(movie);
      if (data) details[movie.id] = toDetails(data);
      else missing.push(`${movie.title} (${movie.year})`);
    } catch (error) {
      missing.push(`${movie.title} (${movie.year}) — ${error.message}`);
    }
    process.stdout.write(".");
    await sleep(DELAY_MS);
  }
  process.stdout.write("\n");

  const body = Object.entries(details)
    .map(([id, value]) => `  ${id}: ${JSON.stringify(value)},`)
    .join("\n");
  fs.writeFileSync(
    DETAILS_FILE,
    `// Extra per-movie facts from OMDb — generated by scripts/fetch-details.js\n` +
      `// (a one-time enrichment, not a live API call). Re-run that script to\n` +
      `// refresh; don't edit by hand.\n` +
      `export const DETAILS = {\n${body}\n};\n\nexport default DETAILS;\n`,
  );
  console.log(`Wrote details for ${Object.keys(details).length}/${MOVIES.length} movies.`);
  if (missing.length > 0) {
    console.log(`Missing ${missing.length}:`);
    missing.forEach((line) => console.log(`  - ${line}`));
  }
};

main();
